<?php $title = 'A propos'; ?>
<?php ob_start (); ?>


<img id="JF" src="<?= $this->baseUrl ?>img/JF.jpg" alt="biographie">

<h2> Jean Forteroche</h2><br>
<h3><em>Acteur et Ecrivain</em></h3><br>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis fermentum arcu, in dapibus nunc. Pellentesque
    eget mauris a odio molestie suscipit ac vel turpis. In eu scelerisque odio. Sed sit amet nisl nunc. Ut tristique
    justo et sem mollis, eget pulvinar nisl ullamcorper. Cras hendrerit leo ut ex pellentesque, ut tincidunt ipsum
    accumsan. In hac habitasse platea dictumst. Nunc suscipit quam quis euismod pellentesque. Nulla feugiat leo ultrices
    leo sollicitudin, eu accumsan velit dictum. Nulla vel elit vel purus aliquam viverra vitae sit amet arcu.

    Nam ligula augue, imperdiet ut blandit eu, porttitor ut urna. Vivamus id posuere eros, nec luctus libero. Quisque in
    iaculis ante, ac viverra ipsum. Maecenas non cursus odio, at lacinia enim. Fusce nulla ligula, sagittis nec lectus
    id, egestas porta urna. Nulla tincidunt lacus purus, rutrum iaculis tellus porta non. Ut in auctor massa, lacinia
    lacinia dui.

    Aenean rutrum a lorem id consequat. Nam feugiat vehicula risus ac dapibus. Sed ligula turpis, varius accumsan lectus
    sed, eleifend aliquam dui. Donec vel lectus quis orci vulputate aliquam quis vel nisl. Orci varius natoque penatibus
    et magnis dis parturient montes, nascetur ridiculus mus. In et urna ac felis interdum commodo nec eget tellus. Ut
    nec magna nec sapien placerat laoreet non et libero.

    Etiam dignissim pharetra orci quis varius. Mauris non arcu enim. Nullam interdum quis ex sit amet pulvinar.
    Curabitur et ex in turpis rutrum suscipit placerat quis mauris. Nullam tempor ex erat, ac vulputate dolor mollis ut.
    Aenean quis massa at dolor pulvinar gravida. Donec tempus a lectus sit amet aliquam. Quisque rhoncus, urna et
    porttitor euismod, mauris mauris ultrices magna, sed malesuada dolor ex ut dolor. Aenean lacus lectus, auctor in
    vestibulum vel, fringilla at turpis. Donec nec est tristique, ultricies dolor nec, ornare libero.
</p>


<?php $content = ob_get_clean (); ?>

<?php require ('template.phtml'); ?>