<?php $title = 'Welcome'; ?>
<?php ob_start (); ?>

    <h2 class="card-title"> Commentaires signalés</h2>

<?php
foreach ($this->comments as $comment) {
    ?>

        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="list-group">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1"> <?= htmlspecialchars ($comment->getAuthor ()) ?></h5>
                                <em><?= $comment->getComment () ?></em>
                                <?php if ($this->is_admin === true) { ?>
                                    <a href="<?= $this->baseUrl ?>public/index.php?action=deleteComment&id=<?= $comment->getId () ?>"
                                     class ="btn btn-outline-warning">Supprimer</a>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <br>
    <?php
}
?>

<?php $content = ob_get_clean (); ?>

<?php require ('template.phtml'); ?>