


<?php $title = 'Welcome'; ?>
<?php ob_start(); ?>


<body>
<h2> Bienvenue dans votre espace</h2>
<p>Bonjour Mr ForteRoche</p>


     <div id="admin_billet">
         <<h2>Gestion des chapitres</h2>
                <ul>
                    <li><a href="index.php?action=admin_BilletManagement_add" title="">Ajouter un chapitre</a></li>
                <li><a href="index.php?action=admin_BilletManagement_edit" title="">Modifier  un chapitre</a></li>
                <li><a href="index.php?action=admin_BilletManagement_delete" title="">Supprimer un chapitre</a></li>
            </ul>
        </>
</div>

 <div id="admin_comment">
     <<h2>Gestion des commentaires</h2>
            <ul>
                <li><a href="index.php?action=admin_commentManagement" title="">Voir les commentaires</a></li>
                <li><a href="index.php?action=admin_commentManagement_signaled" title="">Commentaires signalés</a></li>
                <li><a href="index.php?action=admin_commentManagement_delete" title="">Supprimer un commentaire</a></li>
            </ul>
        </>
</div>

<div id="admin_contact">
    <h2>Gestion des messages</h2>
    <ul>
        <li><a href="index.php?action=admin_commentManagement" title="">Messages lecteurs</a></li>
        <li><a href="index.php?action=admin_commentManagement_signaled" title="">Commentaires signalés</a></li>
        <li><a href="index.php?action=admin_commentManagement_delete" title="">Supprimer un commentaire</a></li>
    </ul>
</>
</div>



</body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>