<?php $title = 'postview'; ?>
<?php ob_start(); ?>


<body>

<?php $title = htmlspecialchars($billet['title']); ?>

<?php ob_start(); ?>

<p><a href="index.php?action=articleList">Retour à la liste des billets</a></p>

<div class="news">
    <h3>
        <?= htmlspecialchars($billet['title']) ?>
        <em>le <?= $billet['billet_date_fr'] ?></em>
    </h3>
    
    <p>
        <?= nl2br(htmlspecialchars($billet['content'])) ?>
    </p>
</div>

<h2>Commentaires</h2>

<form action="index.php?action=addComment&amp;id=<?= $billet['id'] ?>" method="post">
    <div>
        <label for="author">Auteur</label><br />
        <input type="text" id="author" name="author" />
    </div>
    <div>
        <label for="comment">Commentaire</label><br />
        <textarea id="comment" name="comment"></textarea>
    </div>
    <div>
        <input type="submit" />
    </div>

</form>

<?php
foreach ($comments as $comment){

?>
    <p><strong><?= htmlspecialchars($comment['author']) ?></strong> le <?= $comment['comment_date_fr'] ?></p>
    <p><?= nl2br(htmlspecialchars($comment['comment'])) ?></p>
<?php
}
?>

</body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>
