<?php $title = 'postview'; ?>
<?php ob_start(); ?>


<body>

<?php $title = htmlspecialchars($this->billet->getTitle()); ?>


<?php ob_start(); ?>

<p><a href="index.php?action=articleList">Retour à la liste des billets</a></p>

<div class="news">
    <h3>
        <?= htmlspecialchars($this->billet->getTitle()) ?>
        <em>le <?= $this->billet->getBilletDate() ?></em>
    </h3>

    <p>
        <?= nl2br($this->billet->getContent()) ?>
    </p>
</div>


<h2>Commentaires</h2>

<form action="index.php?action=addComment&amp;id=<?= $this->billet->getId() ?>" method="post">
    <div>
        <label for="author">Auteur</label><br />
        <input type="text" id="author" name="author" />
    </div>
    <div>
        <label for="comment">Commentaire</label><br />
        <textarea id="comment" name="comment"></textarea>
    </div>
    <div>
        <input type="submit" value="Envoyer" />
    </div>

</form>


<?php
foreach ($this->comments as $comment){

?>
    <p><strong><?= htmlspecialchars($comment->getAuthor()) ?></strong> le <?= $comment->getCommentDate() ?></p>
    <p><?= nl2br(htmlspecialchars($comment->getComment())) ?></p>
<?php
}

?>

</body>

<?php $content = ob_get_clean(); ?>

    <?php require('template.phtml'); ?>