
<?php $title = 'Chapitres'; ?>
<?php ob_start(); ?>


    <body>
<p>Presentation des differents chapitres / premieres lignes</p>

<h2> Billet 1 </h2>
        <p> </p>
        <a href="http://localhost/PHP/P4/public/index.php?action=article"> Découvrir le nouveau chapitre </a>
<h2> Billet 2 </h2>
        <a href="URL"> Lire </a>
<h2> Billet 3 </h2>
        <a href="URL"> Lire </a>
<h2> Billet 4 </h2>
        <a href="URL"> Lire </a>
<h2> Billet 5 </h2>
        <a href="URL"> Lire </a>
<h2> Billet 6 </h2>
        <a href="URL"> Lire </a>

    </body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>