
<?php $title = 'A propos'; ?>
<?php ob_start(); ?>

    
    <body>
        
        <div class="billet">
    <h3>
        <?= htmlspecialchars($post['title']) ?>
        <em>le <?= $post['creation_date_fr'] ?></em>
    </h3>
    
    <p>
        <?= nl2br(htmlspecialchars($post['content'])) ?>
    </p>
</div>
        
        
         <em><a href="http://localhost/PHP/P4/public/index.php?action=viewComment">Voir les commentaires</a></em><br>
         <em><a href="http://localhost/PHP/P4/public/index.php?action=addComment">Ajouter un commentaire</a></em>
     
  </body>
<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>