
<?php $title = 'Article'; ?>
<?php ob_start(); ?>


<body>

<?php
foreach ($this->billets as $billet) // mettre a jour les views avec $this->billets au lieux de $billets
{
    ?>
    <div class="news">
        <h3>
            <?= htmlspecialchars($billet->getTitle()) ?>
            <em>le <?= $billet->getBilletDate() ?></em>
        </h3>

        <p>
            <em><a href="index.php?action=article&id=<?= $billet->getId() ?>">Lire le chapitre</a></em>
        </p>
    </div>
    <?php
}
?>


</body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>