
<?php $title = 'Article'; ?>
<?php ob_start(); ?>


<body>

<?php
foreach ($billets as $billet)
{
    ?>
    <div class="news">
        <h3>
            <?= htmlspecialchars($billet['title']) ?>
            <em>le <?= $billet['billet_date_fr'] ?></em>
        </h3>

        <p>
            <em><a href="index.php?action=article&id=<?= $billet['id'] ?>">Lire le chapitre</a></em>
        </p>
    </div>
    <?php
}
?>


</body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>