

<?php 
require_once('../model/model.php'); 
require_once('../controller/controller.php'); 
$title = 'A propos'; ?>
<?php ob_start(); ?>


<body>
   

    <h2>Donnez moi votre point de vue </h2>
    <form action="index.php?action=article_viewComment.phtml.phtml" method="post">
        <div>
            <label for="auteur">Auteur</label><br />
            <input type="text" id="author" name="author" />
        </div>
        <div>
            <label for="commentaire">Commentaire</label><br />
            <textarea id="comment" name="comment"></textarea>
        </div>
        <div>
            <input type="submit" />
        </div>
    </form>


</body>


<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>