<?php $title = 'Contact'; ?>
<?php ob_start(); ?>


<body>
  <p>FORMULAIRE CONTACT</p>


  <form action="index.php?action=contact_confirmation>" method="post">
      <div>
          <label for="nom">Nom</label><br />
          <input type="text" id="nom" name="nom" /><br />
          <label for="prenom">Prénom</label><br />
          <input type="text" id="prenom" name="prenom" /><br />
          <label for="adresse_email">Adresse e.mail</label><br />
          <input type="text" id="adresse_email" name="adresse_email" /><br />
      </div>
      <div>
          <label for="message">Message</label><br />
          <textarea id="message" name="message"></textarea>
      </div>
      <div>
          <input type="submit" value="Envoyer" />
      </div>

  </form>

</body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>