<?php $title = 'Article'; ?>
<?php ob_start (); ?>

<article>
    <form action=<?= $this->baseUrl ?>index.php?action=addBillet method="post">
        <div>
            <h2>Nouveau chapitre</h2>
            <label for="title" ></label><br/>
            <input type="text" id="title" name="title" value="Chapitre X : ..."/>
        </div>
        <br>
        <div>
            <label for="content"></label><br/>
            <textarea id="content" name="content"></textarea>
        </div>
        <br>
        <div>
            <input type="submit" id="createArticle" class="btn btn-info" value="Créer"/><br>
        </div>
        <br>
    </form>
</article>
<?php $content = ob_get_clean (); ?>
<?php require ('template.phtml'); ?>