<?php $title = 'Edit Article'; ?>
<?php ob_start (); ?>

<article>
    <form action="<?= $this->baseUrl ?>index.php?action=updateBillet&id=<?= $this->billet->getId () ?>"
          method="post">
        <div>
            <h2>Modification du chapitre</h2>
            <label for="title"></label><br/>
            <input type="text" id="title" name="title" value="<?= htmlspecialchars ($this->billet->getTitle ()) ?>"/>
        </div>
        <div>
            <label for="content"></label><br/>
            <textarea id="content" class="tinymce" name="content"> <?= ($this->billet->getContent ()); ?> </textarea>

            <br>
        </div>

        <div>
            <input type="submit" class="btn btn-info" value="Mise à jour"/>
        </div>
        <br>
    </form>
</article>
<?php $content = ob_get_clean (); ?>
<?php require ('template.phtml'); ?>
