<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=t2rxstudxt2hitdkqrnxkv7rglexrindzow037agtyjcdq0j"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
</head>


<?php $title = 'Modification Billet'; ?>
<?php ob_start();

?>

<body></br>
<p><a href="index.php?action=billetList">Retour à la liste des billets</a></p>
<form action="index.php?action=updateBillet" method="post">
    <div>
        <label for="title">Titre</label><br />
        <input type="text" id="title" name="title" value="<?= htmlspecialchars($this->billet->getTitle()) ?>"/>
    </div></br>
    <div>
        <label for="content">BILLET</label><br />
        <textarea type="textarea" id="content" name="content" value="<?= htmlspecialchars($this->billet->getContent()) ?>"></textarea>
    </div>

    <div>
        <input type="submit" value="Mise à jour" />
    </div>

</form>


</body>
<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>