<?php $title = 'Loging'; ?>
<?php ob_start();
?>

<body>
<h2> Espace Administrateur</h2>
<p>Connectez-vous</p>
    <form action="index?action=adminHome" method="POST">
			<p><label>identifiant<input type="id" name="id"/></label></p>
			<p><label>Mot de passe <input type="password" name="password"/></label></p>
			<p><input type="submit"/></p>
		</form>
</body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>