<?php $title = 'Login'; ?>
<?php ob_start(); ?>



<body>

<h2>Connectez-vous</h2>
    <form action="index.php?action=login" method="POST">
			<p><label> Identifiant<input type="text" name="username" required /></label></p>
			<p><label>Mot de passe <input type="password" name="password" required /></label></p>
			<p><input type="submit"/></p>
    </form>
<h2> S'inscrire </h2>
    <form action="index.php?action=addUser" method="POST">
        <label>Identifiant :</label>
        <input type="text" name="username" required /><br /><br />
        <label>Mot de passe :</label>
         <input type="password" name="password" required /><br /><br />
         <label>Retapez mot de passe :</label>
        <input type="password" name="password2" required /><br /><br />
        <input type="submit" />
    </form>

</body>

<?php $content = ob_get_clean(); ?>

<?php require('template.phtml'); ?>