<!DOCTYPE html>
<html lang="FR">
<head>
    <meta charset="utf-8"/>
    <title><?= $title ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <link href="<?= $this->baseUrl ?>/public/css/style.css" rel="stylesheet"/>
    <script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=t2rxstudxt2hitdkqrnxkv7rglexrindzow037agtyjcdq0j"></script>
    <script>tinymce.init({selector: 'textarea.tinymce'});</script>
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet" />


</head>
<body>
    <header>
    <nav id="menu" class="nav justify-content-center">
        <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link active" id="home-tab" href="<?= $this->baseUrl ?>index.php?action=home" title="Accueil">Accueil</a>
            </li>
            <li class="nav-item"><a class="nav-link active" id="chapitre-tab"  href="<?= $this->baseUrl ?>index.php?action=billetList" title="Chapitres">Chapitres</a>
            </li>
            <li class="nav-item"><a class="nav-link active" id="about-tab" href="<?= $this->baseUrl ?>index.php?action=aboutUs" title="A propos">A propos</a></li>
            <?php if ($this->is_admin === true): ?>
                <li class="nav-item"><a class="nav-link active" id="connexion-tab" href="<?= $this->baseUrl ?>index.php?action=adminHome" title="Admin">Admin</a>
                </li>
            <?php endif; ?>
            <?php if (empty($_SESSION['username'])): ?>
                <li class="nav-item"><a class="nav-link active" id="connexion-tab"  href="<?= $this->baseUrl ?>index.php?action=loginPage" title="Connexion">Connexion</a>
                </li>
            <?php else: ?>
                <li class="nav-item"><a class="nav-link active" id="deconnexion-tab" href="<?= $this->baseUrl ?>index.php?action=logout" title="Deconnexion"><i id=icone class="fas fa-power-off fa-sm"></i></a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
    <div>
        <img id="image1" src="<?= $this->baseUrl ?>public/img/image1.jpg" class="card-img-top" alt="landscape">
        <h3 id="mainTitle"> UN BILLET POUR L'ALASKA </h3>

        <div id="cercle">
            <h3 id="surnameAuteur">Jean</h3>
            <h3 id="nameAuteur">Forteroche</h3>
            <img alt="feather" id="feather" src="https://img.icons8.com/pastel-glyph/50/000000/feather.png">
        </div>
        <div id="separation"></div>
    </div>
</header>
<?php if (isset($_SESSION['message'])) { ?>
    <p class="alert alert-<?= $_SESSION['message']['type'] ?>"><?= $_SESSION['message']['message'] ?></p>
    <?php unset($_SESSION['message']) ?>
<?php } ?>
<article>
    <?= $content ?><br>
</article>

<footer>
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title">Contacts</h5>

            <p class="card-text">BP 266 Avenue Lafayette 75003 Paris Cedex</p>
            <p class="card-text"> unbilletpourlalaska@jforteroche.fr</p>
            <p class="card-text"> Tel : 01 72 65 54 89</p>
        </div>
    </div>
</footer>
</body>
</html>


