<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?= $title ?></title>
        
        <link href="../public/css/style.css" rel="stylesheet"/>
        
       
        <nav>
            <ul id="navigation">
                <li><a href="<?= $this->baseUrl ?>public/index.php?action=home" title="">Acceuil</a></li>
                <li><a href="<?= $this->baseUrl ?>public/index.php?action=articleList" title="">Chapitres</a></li>
                <li><a href="<?= $this->baseUrl ?>public/index.php?action=contact" title="">Contact</a></li>
                <li><a href="<?= $this->baseUrl ?>public/index.php?action=aboutUs" title="">A propos</a></li>
                <li><a href="<?= $this->baseUrl ?>public/index.php?action=login" title="">Admin</a></li>
            </ul>
        </nav>

        <div id=homeTitle> UN BILLET POUR L'ALASKA </div>
    </head>
        
    <body>
        <?= $content ?>
    </body>
</html>

